using System;

namespace lcms2dotnet
{
    public partial struct Signature
    {
        public static readonly Signature AToB0Tag = 0x41324230;                             // 'A2B0'
        public static readonly Signature AToB1Tag = 0x41324231;                             // 'A2B1'
        public static readonly Signature AToB2Tag = 0x41324232;                             // 'A2B2'
        public static readonly Signature BlueColorantTag = 0x6258595A;                      // 'bXYZ'
        public static readonly Signature BlueMatrixColumnTag = 0x6258595A;                  // 'bXYZ'
        public static readonly Signature BlueTRCTag = 0x62545243;                           // 'bTRC'
        public static readonly Signature BToA0Tag = 0x42324130;                             // 'B2A0'
        public static readonly Signature BToA1Tag = 0x42324131;                             // 'B2A1'
        public static readonly Signature BToA2Tag = 0x42324132;                             // 'B2A2'
        public static readonly Signature CalibrationDateTimeTag = 0x63616C74;               // 'calt'
        public static readonly Signature CharTargetTag = 0x74617267;                        // 'targ'
        public static readonly Signature ChromaticAdaptationTag = 0x63686164;               // 'chad'
        public static readonly Signature ChromaticityTag = 0x6368726D;                      // 'chrm'
        public static readonly Signature ColorantOrderTag = 0x636C726F;                     // 'clro'
        public static readonly Signature ColorantTableTag = 0x636C7274;                     // 'clrt'
        public static readonly Signature ColorantTableOutTag = 0x636C6F74;                  // 'clot'
        public static readonly Signature ColorimetricIntentImageStateTag = 0x63696973;      // 'ciis'
        public static readonly Signature CopyrightTag = 0x63707274;                         // 'cprt'
        public static readonly Signature CrdInfoTag = 0x63726469;                           // 'crdi'
        public static readonly Signature DataTag = 0x64617461;                              // 'data'
        public static readonly Signature DateTimeTag = 0x6474696D;                          // 'dtim'
        public static readonly Signature DeviceMfgDescTag = 0x646D6E64;                     // 'dmnd'
        public static readonly Signature DeviceModelDescTag = 0x646D6464;                   // 'dmdd'
        public static readonly Signature DeviceSettingsTag = 0x64657673;                    // 'devs'
        public static readonly Signature DToB0Tag = 0x44324230;                             // 'D2B0'
        public static readonly Signature DToB1Tag = 0x44324231;                             // 'D2B1'
        public static readonly Signature DToB2Tag = 0x44324232;                             // 'D2B2'
        public static readonly Signature DToB3Tag = 0x44324233;                             // 'D2B3'
        public static readonly Signature BToD0Tag = 0x42324430;                             // 'B2D0'
        public static readonly Signature BToD1Tag = 0x42324431;                             // 'B2D1'
        public static readonly Signature BToD2Tag = 0x42324432;                             // 'B2D2'
        public static readonly Signature BToD3Tag = 0x42324433;                             // 'B2D3'
        public static readonly Signature GamutTag = 0x67616D74;                             // 'gamt'
        public static readonly Signature GrayTRCTag = 0x6b545243;                           // 'kTRC'
        public static readonly Signature GreenColorantTag = 0x6758595A;                     // 'gXYZ'
        public static readonly Signature GreenMatrixColumnTag = 0x6758595A;                 // 'gXYZ'
        public static readonly Signature GreenTRCTag = 0x67545243;                          // 'gTRC'
        public static readonly Signature LuminanceTag = 0x6C756d69;                         // 'lumi'
        public static readonly Signature MeasurementTag = 0x6D656173;                       // 'meas'
        public static readonly Signature MediaBlackPointTag = 0x626B7074;                   // 'bkpt'
        public static readonly Signature MediaWhitePointTag = 0x77747074;                   // 'wtpt'
        [Obsolete("Use NamedColor2Tag if possible")]
        public static readonly Signature NamedColorTag = 0x6E636f6C;                        // 'ncol'
        public static readonly Signature NamedColor2Tag = 0x6E636C32;                       // 'ncl2'
        public static readonly Signature OutputResponseTag = 0x72657370;                    // 'resp'
        public static readonly Signature PerceptualRenderingIntentGamutTag = 0x72696730;    // 'rig0'
        public static readonly Signature Preview0Tag = 0x70726530;                          // 'pre0'
        public static readonly Signature Preview1Tag = 0x70726531;                          // 'pre1'
        public static readonly Signature Preview2Tag = 0x70726532;                          // 'pre2'
        public static readonly Signature ProfileDescriptionTag = 0x64657363;                // 'desc'
        public static readonly Signature ProfileDescriptionMLTag = 0x6473636d;              // 'dscm'
        public static readonly Signature ProfileSequenceDescTag = 0x70736571;               // 'pseq'
        public static readonly Signature ProfileSequenceIdTag = 0x70736964;                 // 'psid'
        public static readonly Signature Ps2CRD0Tag = 0x70736430;                           // 'psd0'
        public static readonly Signature Ps2CRD1Tag = 0x70736431;                           // 'psd1'
        public static readonly Signature Ps2CRD2Tag = 0x70736432;                           // 'psd2'
        public static readonly Signature Ps2CRD3Tag = 0x70736433;                           // 'psd3'
        public static readonly Signature Ps2CSATag = 0x70733273;                            // 'ps2s'
        public static readonly Signature Ps2RenderingIntentTag = 0x70733269;                // 'ps2i'
        public static readonly Signature RedColorantTag = 0x7258595A;                       // 'rXYZ'
        public static readonly Signature RedMatrixColumnTag = 0x7258595A;                   // 'rXYZ'
        public static readonly Signature RedTRCTag = 0x72545243;                            // 'rTRC'
        public static readonly Signature SaturationRenderingIntentGamutTag = 0x72696732;    // 'rig2'
        public static readonly Signature ScreeningDescTag = 0x73637264;                     // 'scrd'
        public static readonly Signature ScreeningTag = 0x7363726E;                         // 'scrn'
        public static readonly Signature TechnologyTag = 0x74656368;                        // 'tech'
        public static readonly Signature UcrBgTag = 0x62666420;                             // 'bfd '
        public static readonly Signature ViewingCondDescTag = 0x76756564;                   // 'vued'
        public static readonly Signature ViewingConditionsTag = 0x76696577;                 // 'view'
        public static readonly Signature VcgtTag = 0x76636774;                              // 'vcgt'
        public static readonly Signature MetaTag = 0x6D657461;                              // 'meta'
        public static readonly Signature ArgyllArtsTag = 0x61727473;                        // 'arts'
    }
}